-- ============================================================
-- MONETISATION BEK : Tables pour dons, annuaire, abonnements, pubs
-- ============================================================

-- 1. DONS CITOYENS
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount_dzd NUMERIC NOT NULL,
  amount_eur NUMERIC NOT NULL,
  currency TEXT NOT NULL DEFAULT 'eur',
  status TEXT NOT NULL DEFAULT 'pending',
  stripe_payment_intent_id TEXT UNIQUE,
  supporter_name TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ANNUAIRE COMMERCES
CREATE TABLE IF NOT EXISTS businesses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  description TEXT,
  hours TEXT,
  photos TEXT[] DEFAULT '{}',
  website TEXT,
  is_premium BOOLEAN DEFAULT false,
  premium_expires_at TIMESTAMPTZ,
  stripe_subscription_id TEXT UNIQUE,
  stripe_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ABONNEMENTS UTILISATEURS
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  stripe_subscription_id TEXT UNIQUE,
  stripe_customer_id TEXT,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('monthly', 'yearly')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'canceled', 'expired', 'trialing')),
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RÉGIE PUBLICITAIRE
CREATE TABLE IF NOT EXISTS ad_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  link_url TEXT,
  placement TEXT NOT NULL CHECK (placement IN ('sidebar', 'header', 'inline')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS : ON POUR TOUS LES UTILISATEURS
ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_campaigns ENABLE ROW LEVEL SECURITY;

-- Politiques donations
CREATE POLICY "Allow read donations" ON donations FOR SELECT USING (true);
CREATE POLICY "Allow insert donations" ON donations FOR INSERT WITH CHECK (true);

-- Politiques businesses
CREATE POLICY "Allow read businesses" ON businesses FOR SELECT USING (true);
CREATE POLICY "Allow insert businesses" ON businesses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update own business" ON businesses FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete own business" ON businesses FOR DELETE USING (true);

-- Politiques subscriptions
CREATE POLICY "Allow read own subscription" ON subscriptions FOR SELECT USING (true);
CREATE POLICY("Allow insert subscription") ON subscriptions FOR INSERT WITH CHECK (true);

-- Politiques ad_campaigns (lecture publique, écriture admin uniquement via API)
CREATE POLICY "Allow read ads" ON ad_campaigns FOR SELECT USING (true);

-- Index pour performances
CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);
CREATE INDEX IF NOT EXISTS idx_businesses_category ON businesses(category);
CREATE INDEX IF NOT EXISTS idx_businesses_premium ON businesses(is_premium) WHERE is_premium = true;
CREATE INDEX IF NOT EXISTS idx_ads_active ON ad_campaigns(is_active) WHERE is_active = true;
