-- Créer la table projets
CREATE TABLE IF NOT EXISTS projets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre TEXT NOT NULL,
  objectif TEXT,
  avancement INTEGER DEFAULT 0,
  benevoles INTEGER DEFAULT 0,
  statut TEXT DEFAULT 'Actif',
  date TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Créer la table actualites
CREATE TABLE IF NOT EXISTS actualites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre TEXT NOT NULL,
  categorie TEXT,
  date TEXT,
  image TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activer RLS
ALTER TABLE projets ENABLE ROW LEVEL SECURITY;
ALTER TABLE actualites ENABLE ROW LEVEL SECURITY;

-- Politiques pour projets
CREATE POLICY "Allow all on projets" ON projets
  FOR ALL USING (true) WITH CHECK (true);

-- Politiques pour actualites
CREATE POLICY "Allow all on actualites" ON actualites
  FOR ALL USING (true) WITH CHECK (true);
